# Generated by Django 5.2.7 on 2025-12-09 08:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_project_created_at_project_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="price",
        ),
        migrations.RemoveField(
            model_name="project",
            name="target_amount",
        ),
    ]
