import requests
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
import uuid
from django.utils import timezone
from django.shortcuts import get_object_or_404
from .models import DonationHistory, PaystackDonation
from django.urls import reverse
from django.contrib import messages
from .paystack import checkout
from projects.models import Project
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
import hmac
import hashlib
import json
from decimal import Decimal, InvalidOperation
from django.conf import settings


def _donation_limits():
  min_amount = Decimal(str(getattr(settings, "DONATION_MIN_AMOUNT", 100)))
  max_amount = Decimal(str(getattr(settings, "DONATION_MAX_AMOUNT", 1000000)))
  return min_amount, max_amount

def donation_checkout(request, donation_id):
  project = Project.objects.get(id=donation_id)
  min_amount, max_amount = _donation_limits()
  context = {
    "project": project,
    "min_amount": min_amount,
    "max_amount": max_amount,
  }
  return render(request, "donations/donation_checkout_form.html", context)

def donation_success(request, project_id):
    project = Project.objects.get(id=project_id)
    # print(f"User: {request.user}, Project: {project}")

    # Get the most recent successful donation for this user and project
    donation = DonationHistory.objects.filter(
        project=project,
        donation_status=True
    ).order_by('-date').first()

    if donation:
        amount = donation.amount
        email = donation.email
        first_name =donation.first_name
        last_name = donation.last_name
    else:
        None

    return render(request, 'donations/donation_success.html', {
        'project': project,
        'email' : email,
        'amount': amount,
        'first_name': first_name,
        'last_name': last_name
    })
# no need to login 
def donation_failed(request, project_id):

  project = Project.objects.get(id=project_id)
    
  # Get the most recent failed donation for this user and project (optional)
  donation = DonationHistory.objects.filter(
      project=project,
      donation_status=False
  ).order_by('-date').first()
  
  
  return render(request, 'donations/donation_failed.html', {
      'project': project,
      'donation_id': donation.donation_id
  })


def create_paystack_checkout_session(request, project_id):
    project = Project.objects.get(id=project_id)

    if request.method == "POST":
        email_text = request.POST.get("donor_email")
        amount_text = request.POST.get("amount")
        first_name_text = request.POST.get("first_name")
        last_name_text = request.POST.get("last_name")
        try:
            amount = Decimal(amount_text)
        except (InvalidOperation, TypeError):
            messages.error(request, "Enter a valid numeric amount.")
            return redirect('donation', donation_id=project_id)

        # validate min/max
        if amount <= 0:
            messages.error(request, "Amount must be greater than zero.")
            return redirect('donations:donation', donation_id=project_id)
        
        donation_id = f"donation_{uuid.uuid4()}"
        # /payment-success/2/
        # payment_success_url = reverse('donations:donation-success', kwargs={'project_id': project_id})
        # http://domain.com/payment-success/2/ 
        # callback_url = f"{request.scheme}://{request.get_host()}{payment_success_url}"
        # Paystack expects amount in kobo (or cents) as integer
        amount_in_kobo = int(amount * 100)

        checkout_data = {
        "email": email_text,
        "amount": amount_in_kobo,  # in kobo 
        "currency": "KES",
        "channels": ["card", "bank_transfer", "bank", "ussd", "qr", "mobile_money"],
        "reference": donation_id, # generated by developer
        # "callback_url": callback_url,
        "label": f"Checkout For {project.name}"
        }
        print("The checkout data payload sent to paystack is as follows:")
        print(checkout_data)
        print("End of paystack checkout data sent")

        status, check_out_session_url_or_error_message, response_data = checkout(checkout_data)
        PaystackDonation.objects.create(
            email = email_text,
            amount = amount_text,
            first_name = first_name_text,
            last_name = last_name_text,
            initialize_response = response_data,
            donation_id = donation_id,
            project_id = project_id

        )

        if status:
            return redirect(check_out_session_url_or_error_message)
        else:
            messages.error(request, check_out_session_url_or_error_message)
            return redirect('donations:donation',donation_id=project_id)
    # GET: render form to enter amount
    return render(request, 'donations/donation_checkout_form.html', {'project': project})

@csrf_exempt
def paystack_webhook(request):
    secret = settings.PAYSTACK_TEST_SECRET_KEY
    request_body = request.body
    
    hash = hmac.new(secret.encode('utf-8'), request_body, hashlib.sha512).hexdigest()
    
    if hash == request.META.get('HTTP_X_PAYSTACK_SIGNATURE'):
        webhook_post_data = json.loads(request_body)
       
        if webhook_post_data["event"] == "charge.success":
           
            data = webhook_post_data["data"]            
            donation_id = data.get("reference")

            amount_paid_kobo = data.get("amount")
            amount_paid = Decimal(amount_paid_kobo) / 100

            paystack_donation = PaystackDonation.objects.select_related("project").filter(
                donation_id = donation_id,
                amount = amount_paid,
                is_success = False
            ).first()

            if not paystack_donation:
                print("Recieved invalid data")
                return HttpResponse(status=200)
            

            donation_history=DonationHistory.objects.create(
                donation_id = paystack_donation.donation_id,
                email = paystack_donation.email,
                donation_status = True,
                project = paystack_donation.project,
                amount = amount_paid,
                first_name = paystack_donation.first_name,
                last_name = paystack_donation.last_name
            )
            paystack_donation.donation_history  = donation_history
            paystack_donation.call_back_response=webhook_post_data
            paystack_donation.completed_at=timezone.now()
            paystack_donation.is_success=True
            paystack_donation.save()

            #send email to user on successful payment
            # send_payment_success_email(user.email, product_id)

    return HttpResponse(status=200)

   