# Generated by Django 5.2.7 on 2025-11-16 22:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationhistory",
            name="donation_id",
            field=models.CharField(
                default=uuid.UUID("b8019558-6a86-4918-b4f9-c9af77258904"),
                max_length=225,
            ),
        ),
    ]
