# Generated by Django 5.2.7 on 2025-11-16 22:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0002_alter_donationhistory_donation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationhistory",
            name="donation_id",
            field=models.CharField(
                default=uuid.UUID("f347218b-ff35-43bf-9104-1595e2b25efa"),
                max_length=225,
            ),
        ),
    ]
