# Generated by Django 5.2.7 on 2025-11-16 22:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0003_alter_donationhistory_donation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationhistory",
            name="donation_id",
            field=models.CharField(
                default=uuid.UUID("900dea54-6f71-44b5-81f6-50c13042ed55"),
                max_length=225,
            ),
        ),
    ]
