# Generated by Django 5.2.7 on 2025-11-16 22:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0004_alter_donationhistory_donation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationhistory",
            name="donation_id",
            field=models.CharField(
                default=uuid.UUID("f1b5fdaf-0a6c-4d3a-a077-31cd6e1d17c3"),
                max_length=225,
            ),
        ),
    ]
