# Generated by Django 5.2.7 on 2025-11-17 07:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0005_alter_donationhistory_donation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationhistory",
            name="donation_id",
            field=models.CharField(
                default=uuid.UUID("f3b04941-8ef6-4279-adeb-9f1da1890f59"),
                max_length=225,
            ),
        ),
    ]
