# Generated by Django 5.2.7 on 2025-11-17 07:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0006_alter_donationhistory_donation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationhistory",
            name="donation_id",
            field=models.CharField(
                default=uuid.UUID("5f0c7087-f311-453b-be14-8ec103adafd8"),
                max_length=225,
            ),
        ),
    ]
