# Generated by Django 5.2.7 on 2025-12-01 11:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_alter_donationhistory_donation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationhistory',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donationhistory',
            name='donation_id',
            field=models.CharField(default=uuid.uuid4, max_length=225),
        ),
    ]
