# Generated by Django 5.2.7 on 2025-11-22 10:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_alter_donationhistory_donation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationhistory',
            name='donation_id',
            field=models.CharField(default=uuid.UUID('ed5f9d30-ffa5-44c4-aa15-8853db41628f'), max_length=225),
        ),
    ]
