# Generated by Django 5.2.7 on 2025-11-22 11:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_alter_donationhistory_donation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationhistory',
            name='donation_id',
            field=models.CharField(default=uuid.UUID('1c64194d-b059-43fa-9793-270c54ae8371'), max_length=225),
        ),
    ]
