# Generated by Django 5.2.7 on 2025-12-09 08:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0009_alter_donationhistory_donation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationhistory",
            name="donation_id",
            field=models.CharField(
                default=uuid.UUID("c03cdd58-2dbc-4e20-8c78-5627477938c7"),
                max_length=225,
            ),
        ),
    ]
