# Generated by Django 5.2.7 on 2025-12-12 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_donationhistory_is_anonymous_and_more'),
        ('donations', '0010_alter_donationhistory_donation_id'),
    ]

    operations = [
    ]
