# Generated by Django 5.2.7 on 2025-12-28 14:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0011_merge_20251212_1015"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donationhistory",
            name="is_anonymous",
        ),
        migrations.RemoveField(
            model_name="donationhistory",
            name="user",
        ),
        migrations.AddField(
            model_name="donationhistory",
            name="email",
            field=models.EmailField(default="noemail@example.com", max_length=254),
        ),
        migrations.AddField(
            model_name="donationhistory",
            name="first_name",
            field=models.CharField(
                blank=True, default="Anonymous", max_length=150, null=True
            ),
        ),
        migrations.AddField(
            model_name="donationhistory",
            name="last_name",
            field=models.CharField(
                blank=True, default="User", max_length=150, null=True
            ),
        ),
        migrations.AlterField(
            model_name="donationhistory",
            name="donation_id",
            field=models.CharField(
                default=uuid.UUID("00ade118-da43-4f77-9d76-e1e31c12b79b"),
                max_length=225,
            ),
        ),
    ]
