# Generated by Django 5.2.7 on 2025-12-12 13:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_merge_20251212_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationhistory',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='donationhistory',
            name='donation_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=225),
        ),
    ]
