# Generated by Django 5.2.7 on 2025-12-28 16:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0012_remove_donationhistory_is_anonymous_and_more"),
        ("projects", "0004_remove_project_price_remove_project_target_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationhistory",
            name="donation_id",
            field=models.CharField(
                default=uuid.UUID("a78ec784-84c5-4162-8ec8-a5b9be304004"),
                max_length=225,
            ),
        ),
        migrations.CreateModel(
            name="PaystackDonation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(default="noemail@example.com", max_length=254),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, default="Anonymous", max_length=150, null=True
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, default="User", max_length=150, null=True
                    ),
                ),
                (
                    "initialize_response",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "call_back_response",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "donation_id",
                    models.CharField(
                        default=uuid.UUID("32aba3b8-3c7a-45b1-825d-376626cad4f8"),
                        max_length=225,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_success", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "donation_history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="donations.donationhistory",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
