# Generated by Django 5.2.7 on 2025-12-28 17:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0013_alter_donationhistory_donation_id_paystackdonation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationhistory",
            name="donation_id",
            field=models.CharField(
                default=uuid.UUID("6c960d11-10ed-45ea-82c7-b4795f569fcd"),
                max_length=225,
            ),
        ),
        migrations.AlterField(
            model_name="paystackdonation",
            name="donation_id",
            field=models.CharField(
                default=uuid.UUID("5d5f17ca-17ee-497b-abc7-4cc4cddbec56"),
                max_length=225,
            ),
        ),
    ]
